ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "termsAcceptedAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "termsSignedName" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "termsVersion" TEXT;
